### PR TITLE
test: fix flaky test for getEvaluations using custom timeout

### LINKED ISSUE #140: test: fix `getEvaluations` flaky test
This test fails randomly due to slow CI.

```
io.bucketeer.sdk.android.internal.remote.ApiClientImplTest > getEvaluations - custom timeout FAILED
    com.google.common.truth.AssertionErrorWithFacts at ApiClientImplTest.kt:194
```

https://github.com/bucketeer-io/android-client-sdk/actions/runs/8261127634/job/22597824194

### PR DESCRIPTION
**Pull request by cre8ivejp**
Fixes #140

### CODE REVIEW

File: bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/remote/ApiClientImplTest.kt [hunk 1]
```diff
@@ -177,22 +177,22 @@ internal class ApiClientImplTest {
...
       featureTag = "feature_tag_value",
       moshi = moshi,
-      defaultRequestTimeoutMillis = 1_000,
     )
 
     val (millis, result) = measureTimeMillisWithResult {
       client.getEvaluations(
         user = user1,
         userEvaluationsId = "user_evaluation_id",
+        timeoutMillis = TimeUnit.SECONDS.toMillis(2),
```
Comment (cre8ivejp) [inline bucketeer/src/test/kotlin/io/bucketeer/sdk/android/internal/remote/ApiClientImplTest.kt:186]: Because this case is to test using a custom timeout, it should be set here instead of setting the default timeout in the constructor.
